version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  prepare-dependencies:
    executor: my-executor
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-deps-{{ checksum "requirements.txt" }}
            - python-deps
      - build
      - save_cache:
          key: python-deps-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_and_test:
    executor: my-executor
    resource_class: medium
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            pipenv run python manage.py test
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - build
      - heroku/deploy-via-git:
          force: true

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - prepare-dependencies
      - build_and_test:
          requires:
            - prepare-dependencies
          when: always
      - deploy:
          requires:
            - build_and_test
          when: always
